sky:
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    host: ${sky.datasource.host}
    port: ${sky.datasource.port}
    database: ${sky.datasource.database}
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
  shop:
    address: ${sky.shop.address}
  baidu:
    ak: ${sky.baidu.ak}